### ISSUE TITLE
Wordpress Installation goes nowhere

### ISSUE THREAD

**Issue by MurphyDoe0815** [DjNaufrago/LAMP-Wordpress-installer#1]
The lamp installation works fantastically. Good work. Unfortunately, the Wordpress installation is not possible. Neither a download of Wordpress nor any changes are noticeable here. 
Do I have to download Wordpress first and from where should the bash be activated ? no matter where - the log.txt is not described.

Greetings

**Comment by DjNaufrago** [comment]
Hello greetings. Follow the steps given in the instructions that are in the repository readme and you should have no problems (INSTRUCTIONS TO INSTALL WORDPRESS): change the owner of the web directory, move to that directory and download the script inside. From there, run the script as a normal user.

**_To keep in mind:_**
- If you don't change the owner of the web directory, you won't be able to download the script inside it.
- The script must be run in the web directory.
- If you run the script as super user, the command-line interface for WordPress will not work.

I just tried it following the steps and had no problems.

**Comment by MurphyDoe0815** [comment]
sorry, but it doesn't want to.
maybe i should have said that i have a ubuntu lxc running under proxmox. it's just difficult not to log in as root in the container and it causes problems afterwards.
the option "-- install as root anyway" didn't work either. 

so i will install wordpress the traditional way.
by the way, download caused problems in the script because curl is not installed. maybe that should be included.

Greetings

**Comment by DjNaufrago** [comment]
1 - I think the script can be adapted to run in LXC as root. Maybe changing the way of executing the commands to something like:
`su - www-data -c command`

2 - I have already added curl to be installed, however, in the versions that I have tried it was already pre-installed.

Good luck

**Comment by MurphyDoe0815** [comment]
installing the curl in the script works perfectly  and was a good idea !

unfortunately the installation of the wordpress script hangs up.
I have created a user and made the script executable.
then came this message

 * ERROR * MARIADB ROOT KEY IS EMPTY.

 * IF YOU KNOW IT, COPY IT TO THE BEGINNING OF THE FILE

 * BETWEEN THE QUOTES AFTER DB_ROOT_PASS.

**Comment by DjNaufrago** [comment]
The script gets the database key from the previous LAMP installation as long as the same user is running both scripts. This is not restrictive, but would be recommended.

You can bypass this by copying the database key to the beginning of the script. Substituting in DB_ROOT_PASS="${MDBRP: -16}" with something like this DB_ROOT_PASS="MYDBPASSWORD".

Another alternative without making any changes to the script is to copy the log file from the previous installation to the home of the user running it.

**Comment by MurphyDoe0815** [comment]
i'm really sorry. i've now tried everything i could think of. in all of it, it didn't even get the script to run enough to download wordpress.

the non-root variant with the entry went just as far as the root variant. with the extra user, there was also the constant "give me your password" and "i can't create".
by the way, i changed the script according to your instructions.

lamp is great - wordpress unfortunately not yet. at least under proxmox and a ubuntu lxc.

but i will try it more often. you have a really interesting approach !!!!

**Comment by DjNaufrago** [comment]
I had some time and was doing research. I was able to get root to run the command to download the package by noticing the following:

- The www-data user and group are created by apache to manipulate the web directory. Only they should have access. Making changes as root user directly is a very bad idea.

- The recommended thing then is to use an additional user besides root, add it to the www-data group and "temporarily" assign permissions to the user to write to the web directory. On Ubuntu Server and Desktop, this user already exists by default (ubuntu). I think in LXC you would have to create it.

- The LAMP script adds the user (ubuntu) to the www-data group and the script to install WordPress temporarily assigns the permissions as I mentioned in the previous point.

- Once the requirement is met, you can run the wp client as root and make changes to the settings. For example:

`sudo -u ubuntu -i -- wp core download --path=/var/www/html`

The --path option at the end is essential since when running as another user, it will look to make changes to your home directory.

Another example would be something like this:

`sudo -u ubuntu -i -- wp core config --dbhost=localhost --dbprefix=wp_ --dbname=dbwordpress --dbuser=userwp --dbpass=abc123 --path=/var/www/html`

**Comment by MurphyDoe0815** [comment]
unfortunately it still stops and it doesn't really want to. no idea if it's just proxmox lxc.

I found a script on the net that ran and also set all the folders correctly.

maybe you will find something for you that overcomes the stops.

here you can find the script: 

(https://linux.how2shout.com/script-to-install-lamp-wordpress-on-ubuntu-20-04-lts-server-quickly-with-one-command/)
